#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules/swig-templates/bin/node_modules:/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules/swig-templates/node_modules:/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules:/mnt/c/blog/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules/swig-templates/bin/node_modules:/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules/swig-templates/node_modules:/mnt/c/blog/node_modules/.pnpm/swig-templates@2.0.3/node_modules:/mnt/c/blog/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../swig-templates@2.0.3/node_modules/swig-templates/bin/swig.js" "$@"
else
  exec node  "$basedir/../../../../../swig-templates@2.0.3/node_modules/swig-templates/bin/swig.js" "$@"
fi
