#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules/hexo-bunyan/bin/node_modules:/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules/hexo-bunyan/node_modules:/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules:/mnt/c/blog/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules/hexo-bunyan/bin/node_modules:/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules/hexo-bunyan/node_modules:/mnt/c/blog/node_modules/.pnpm/hexo-bunyan@1.0.0/node_modules:/mnt/c/blog/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../hexo-bunyan@1.0.0/node_modules/hexo-bunyan/bin/bunyan" "$@"
else
  exec node  "$basedir/../../../../../hexo-bunyan@1.0.0/node_modules/hexo-bunyan/bin/bunyan" "$@"
fi
